/**
 * Trusts the user's own certificate authorities on Android.
 *
 * Android has ignored user-installed CAs since API 24 unless an app says
 * otherwise, so a self-hoster who puts their server behind Caddy's
 * `tls internal` — or any private CA — and installs that root on their phone
 * still cannot reach it: the handshake dies with "Trust anchor for
 * certification path not found". iOS trusts a user-enabled root system-wide,
 * so this was an Android-only gap, and one with no workaround short of
 * obtaining a publicly-trusted certificate for a LAN hostname.
 *
 * Installing the root is already a deliberate act the OS warns about, and it
 * is the same trust the phone's browser extends. The app is not lowering a
 * bar here, it is declining to ignore the user's own answer — nothing else
 * about verification changes, and an untrusted certificate is still refused.
 *
 * **`cleartextTrafficPermitted` has to be restated.** A network security
 * config *replaces* the manifest's `usesCleartextTraffic`, so leaving it out
 * would silently turn `http://` servers off on API 28+ — which is most of the
 * reason someone runs this app on a LAN. `app.json` sets that flag to true
 * through `expo-build-properties`; this keeps it true.
 *
 * The file this writes is checked in under `android/` as well, because
 * nothing runs `expo prebuild` in CI — the checked-in copy is what ships.
 * This plugin is what makes a prebuild reproduce it rather than drop it.
 */
const { withAndroidManifest, withDangerousMod, AndroidConfig } = require('@expo/config-plugins');
const fs = require('fs');
const path = require('path');

const RESOURCE_NAME = 'network_security_config';

const NETWORK_SECURITY_CONFIG = `<?xml version="1.0" encoding="utf-8"?>
<!--
  Generated by plugins/withUserCaTrust.js — change it there, not here.

  cleartextTrafficPermitted restates app.json's usesCleartextTraffic: this
  file replaces that manifest flag rather than adding to it, so omitting it
  would turn http:// servers off.

  The user entry is the point of the file: Android ignores user-installed
  CAs from API 24 up without it, which makes a private CA (Caddy's
  "tls internal", for one) unusable where iOS and every browser accept it.
-->
<network-security-config>
  <base-config cleartextTrafficPermitted="true">
    <trust-anchors>
      <certificates src="system" />
      <certificates src="user" />
    </trust-anchors>
  </base-config>
</network-security-config>
`;

const withConfigFile = config =>
  withDangerousMod(config, [
    'android',
    async modConfig => {
      const directory = path.join(
        modConfig.modRequest.platformProjectRoot,
        'app',
        'src',
        'main',
        'res',
        'xml'
      );
      await fs.promises.mkdir(directory, { recursive: true });
      await fs.promises.writeFile(
        path.join(directory, `${RESOURCE_NAME}.xml`),
        NETWORK_SECURITY_CONFIG,
        'utf8'
      );
      return modConfig;
    },
  ]);

const withManifestReference = config =>
  withAndroidManifest(config, modConfig => {
    const application = AndroidConfig.Manifest.getMainApplicationOrThrow(modConfig.modResults);
    application.$['android:networkSecurityConfig'] = `@xml/${RESOURCE_NAME}`;
    return modConfig;
  });

module.exports = config => withManifestReference(withConfigFile(config));
module.exports.NETWORK_SECURITY_CONFIG = NETWORK_SECURITY_CONFIG;
module.exports.RESOURCE_NAME = RESOURCE_NAME;
